if: branch = develop OR type = pull_request
language: node_js
node_js:
  - "8.3"
cache: npm
before_script:
  - npm install -g npm@latest
jobs:
  include:
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      install:
        - npm install -g react-native-cli
      script:
        - bash install-certificates.sh
        - react-native run-ios --configuration Release
        - ls -R ios
        - ls -R node_modules/react-native/scripts
