if: branch = develop OR type = pull_request
language: node_js
node_js:
  - "8.3"
cache: npm
before_install:
  - npm install -g npm@latest
  - npm install
jobs:
  include:
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      install:
        - npm install -g react-native-cli
      script:
        - cd ios
        - bash install-certificates.sh
        - node --version
        - npm --version
        - react-native run-ios --configuration Release
        - ls -R ../ios
        - ls -R ../node_modules/react-native/scripts
