dist: trusty
language: node_js
node_js:
  - "node"
cache: npm
before_install:
  - sudo apt-get update &>/dev/null && sudo apt-get install -y openjdk-8-jdk &>/dev/null && sudo rm -rf /var/lib/apt/lists/* &>/dev/null
  - wget -q -O sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && mkdir android-sdk && unzip -qq -d android-sdk sdk.zip && rm -rf sdk.zip
  - yes | ./android-sdk/tools/bin/sdkmanager "build-tools;27.0.3" "platforms;android-27" &>/dev/null
  - export ANDROID_HOME=$PWD/android-sdk
  - npm install -g react-native-cli
  - npm install -g netlify-cli@next
script:
  - bash deploy.sh
