dist: trusty
language: node_js
node_js:
  - "node"
cache: npm
components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
before_install:
  #- export ANDROID_HOME=$PWD/android-sdk
  - yes | sdkmanager "platforms;android-27"
  - whereis sdkmanager
  - type -a sdkmanager
  - npm install -g react-native-cli
  - npm install -g netlify-cli@next
script:
  - bash deploy.sh
