dist: trusty
language: node_js
node_js:
  - "node"
before_script:
  - export HEAD_BRANCH=$(echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | tr '/' '-')
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-23
          - android-27
          - build-tools-27.0.3
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - nvm install node
        - npm install -g react-native-cli
        - npm install
        - react-native link
        - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      script:
        - cd android
        - ./gradlew -q -x bundleReleaseJsAndAssets assembleRelease
        - cd ..
        - bash testfairy-uploader.sh android/app/build/outputs/apk/release/app-release.apk

    - language: objective-c
      os: osx
      sudo: required
      node_js: "node"
      before_install:
        - nvm install node
        - npm install -g react-native-cli
        - npm install
        - react-native link
        - react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios/assets
      script:
        - cd ios
        - xcodebuild -project curb.xcodeproj -scheme curb -configuration Release clean archive -archivePath curb.xcarchive -allowProvisioningUpdates DEVELOPMENT_TEAM="A1B2C3D4E5"
        - xcodebuild -exportArchive -archivePath curb.xcarchive -exportOptionsPlist exportOptions.plist -exportPath curb.ipa
        - cd ..
        - bash testfairy-uploader.sh ios/curb.ipa
#    - language: node_js
#      cache: npm
#      before_script:
#        - npm install -g netlify-cli@next
#      script:
#        - npm run web-build
#        - bash deploy-netlify.sh
