if: branch = develop OR type = pull_request

if: branch = develop
  env:
    - CURB_BUILD="production"
    - CURB_VERSION="/${TRAVIS_BRANCH}"

if: type = pull_request
  env:
    - CURB_BUILD="development"
    - CURB_VERSION=$(echo ${TRAVIS_PULL_REQUEST_BRANCH} | tr '/' '-')

cache: npm

before_install:
  - nvm install node
  - npm install

jobs:
  include:
    - stage: Web
      language: node_js
      before_install:
        - set -e
      install:
        - npm install -g netlify-cli@next
      before_script:
        - npm run web-build:${CURB_BUILD}
      script:
        - bash deploy-netlify.sh

    - stage: Android
      language: android
      android:
        components:
          - tools
          - android-23
          - android-28
          - build-tools-28.0.3
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - set -e
      install:
        - npm install -g react-native-cli
      before_script:
        - npm run mobile-build-android:${CURB_BUILD}
      script:
        - cd android
        - openssl aes-256-cbc -k "$CURB_STORE_ENCRYPT_PASSWORD" -in app/curb.keystore.enc -d -a -out app/curb.keystore
        - ./gradlew -q -x bundleReleaseJsAndAssets assembleRelease
        - zip -q -r symbols.zip app/build/intermediates/symbols/release/R.txt
        - bash ../.travis/deploy-testfairy.sh app/build/outputs/apk/release/app-release.apk symbols.zip
      before_cache:
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
        - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

    - stage: iOS
      os: osx
      language: objective-c
      before_install:
        - set -e      
      install:
        - npm install -g react-native-cli
      before_script:
        - npm run mobile-build-ios:${CURB_BUILD}
      script:
        - cd ios
        - bash install-certificates.sh
        - xcodebuild archive -quiet -project Curb.xcodeproj -scheme Curb -configuration Release clean -archivePath curb.xcarchive
        - xcodebuild -quiet -exportArchive -archivePath curb.xcarchive -exportOptionsPlist exportOptions.plist -exportPath export
        - ditto -c -k --keepParent -rsrc curb.xcarchive/dSYMs/curb.app.dSYM symbols.zip
        - bash ../.travis/deploy-testfairy.sh export/curb.ipa symbols.zip
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/node_modules/**/*.log
