if: branch = develop OR type = pull_request
language: node_js
cache: npm
before_install:
  - export CURB_VERSION=$(echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | tr '/' '-')
  - export CURB_BUILD=$([[ $CURB_VERSION == "develop" ]] && echo "production" || echo "development")
  - nvm install 8.3.0
  - nvm alias default 8.3.0
  - npm install
jobs:
  include:
    - stage: Web
      install:
        - npm install -g netlify-cli@next
      before_script:
        - npm run web-bundle:${CURB_BUILD}
      script:
        - bash .travis/deploy-web.sh || travis_terminate 1
    - stage: Android
      language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-23
          - android-28
          - build-tools-28.0.3
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      install:
        - npm install -g react-native-cli
      before_script:
        - npm run mobile-bundle-android:${CURB_BUILD}
      script:
        - cd android
        - bash ../.travis/build-android.sh || travis_terminate 1
        - bash ../.travis/deploy-android.sh || travis_terminate 1
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      install:
        - npm install -g react-native-cli
      before_script:
        - npm run mobile-bundle-ios:${CURB_BUILD}
      script:
        - cd ios
        - bash ../.travis/build-ios.sh || travis_terminate 1
        - bash ../.travis/deploy-ios.sh || travis_terminate 1
