if: branch = develop OR type = pull_request

before_install:
  - nvm install 11.9.0
  - npm install

jobs:
  include:
    - stage: Build iOS
      os: osx
      language: objective-c
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
      install:
        - npm install -g react-native-cli
      script:
        - bash install-certificates.sh
        - react-native run-ios --configuration Release
        - ls -R ios
        - ls -R node_modules/react-native/scripts
      before_cache:
        - rm -f $TRAVIS_BUILD_DIR/node_modules/**/*.log
