if: branch = develop OR type = pull_request
language: node_js
  - "8.3.0"
cache: npm
before_install:
  - nvm install 8.3.0
  - nvm alias default 8.3.0
  - npm install
jobs:
  include:
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      install:
        - npm install -g react-native-cli@latest
      script:
        - cd ios
        - bash install-certificates.sh
        - xcodebuild -quiet archive -project curb.xcodeproj -scheme curb -configuration Release -archivePath curb.xcarchive -allowProvisioningUpdates
        - ls -R
        - xcodebuild -quiet -exportArchive -archivePath curb.xcarchive -exportOptionsPlist exportOptions.plist -exportPath export
        - ls -R
