if: branch = develop OR type = pull_request
language: node_js
node_js:
  - "8.3.0"
cache: npm
env:
  global:
    - CURB_BUILD=$(bash .travis/curb-build.sh)
    - CURB_VERSION=$(bash .travis/curb-version.sh)
before_install:
  - nvm install 8.3.0
  - nvm alias default 8.3.0
  - npm install
jobs:
  include:
    - stage: Web
      install:
        - npm install -g netlify-cli@2.11.7
      before_script:
        - npm run web-bundle:${CURB_BUILD} || travis_terminate 1
      script:
        - bash .travis/deploy-web.sh || travis_terminate 1
      after_failure:
        - bash .travis/send-discord-logs.sh failure $WEBHOOK_URL
    - stage: Android
      language: android
      dist: trusty
      jdk: orackejdk8
      env:
        - SKIP_BUNDLING=1
      android:
        components:
          - tools
          - android-23
          - android-28
          - build-tools-28.0.3
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      install:
        - npm install -g react-native-cli
      before_script:
        - echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - npm run mobile-bundle-android:${CURB_BUILD} || travis_terminate 1
      script:
        - cd android
        - bash ../.travis/build-android.sh || travis_terminate 1
        - bash ../.travis/deploy-android.sh || travis_terminate 1
        - cd ..
      after_failure:
        - bash .travis/send-discord-logs.sh failure $WEBHOOK_URL
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - SKIP_BUNDLING=1
      install:
        - npm install -g react-native-cli
      before_script:
        - npm run mobile-bundle-ios:${CURB_BUILD} || travis_terminate 1
      script:
        - cd ios
        - bash ../.travis/build-ios.sh || travis_terminate 1
        - bash ../.travis/deploy-ios.sh || travis_terminate 1
        - cd ..
      after_success:
        - bash .travis/send-discord-logs.sh success $WEBHOOK_URL
      after_failure:
        - bash .travis/send-discord-logs.sh failure $WEBHOOK_URL
