if: branch = develop OR type = pull_request
language: node_js
cache: npm
before_install:
  - nvm install 8.3.0
  - npm install
jobs:
  include:
    - stage: iOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      install:
        - npm install -g react-native-cli@latest
      script:
        - cd ios
        - bash install-certificates.sh
        - cd ..
        - node --version
        - npm --version
        - react-native run-ios --configuration Release
        - ls -R ios
        - ls -R node_modules/react-native/scripts
